//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Histories = new HashSet<History>();
            this.Scheduled_visitations = new HashSet<Scheduled_visitations>();
        }
    
        public long doctor_id { get; set; }
        public long hospital_id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string last_name { get; set; }
        public string specialization { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Scheduled_visitations> Scheduled_visitations { get; set; }
    }
}
