//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Histories = new HashSet<History>();
            this.Scheduled_visitations = new HashSet<Scheduled_visitations>();
        }
    
        public long hospital_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Scheduled_visitations> Scheduled_visitations { get; set; }
    }
}
